name: insan_muslim
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dartz: ^0.10.1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_phoenix: ^1.1.1
  flutter_qiblah: ^2.1.0
  flutter_svg: ^2.0.4
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  hijri: ^3.0.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  time_picker_sheet: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splashLogo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splashLogo.png

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
